### ISSUE TITLE
Error in (foldl) function. Band and others with (...) in current version support only 3 arguments. [solution inside]

### ISSUE THREAD

**Issue by MAGGen-hub** [horvand/lua54-bit32#1]
If function:
```
local function foldl(f, init, ...)
  local fst, rest = ...
  if (fst == nil) then 
    return init
  end
  return foldl(f, f(init, fst), rest)
end
```

This part contain an error: ` local fst, rest = ...`
`rest` in this situation will save only second arg and that mean only first 3 args will be supported.

To make it work as expected you need to use `table.pack`, `table.unpack` and `table.remove` funcs:
```
local function foldl(f, init, ...)
  local rest = {...} -- equal to `table.pack` (packs `...` into table)
  local fst = table.remove(rest,1) -- removes first item from `rest` table and loads it into `fst` variable
  if (fst == nil) then 
    return init
  end
  return foldl(f, f(init, fst), table.unpack(rest)) -- unpacks `rest` into correct `...`
end
```

Code above should work correctly but it will work way better if you wrap `...` with `{...}` before calling `foldl` like this:
```
function bit32.band(...)
  return foldl(function(x,y) return  x & to32(y) end, MAX_32, {...}) --wraped `...`. Same stuff must be done for `bor` and others
end
```
This kind of solution will allow you to push only 3 arguments into `foldl` where third one is table with args. 
That will allow you to skip a few steps like table constructor calls (`{...}` - table wraper) and `table.unpack` at the end.
Also functions that has no multy-argument support are faster so technically that should increace your lib performance.
New func with no varargs:
```
local function foldl(f, init, rest)
  local fst = table.remove(rest,1)
  if (fst == nil) then 
    return init
  end
  return foldl(f, f(init, fst), rest)
end
```

Thank you for your attention. And good luck in future development.

**Comment by horvand** [comment]
Hi,

Thank you for spotting the problem. It is a nasty bug, the current code works in trivial cases, but it fails to do what it promises, that is, be a drop-in replacement to keep legacy code working. I got some cryptography library working with it, without spotting the issue.

I plan to keep the vararg logic and only fix `foldl`, since I want to keep the code as simple as possible, the code shouldn't be used anyways if performance is desired.
